_veh = _this select 0;
_veh addItemcargoglobal ["ACE_morphine", 20];
_veh addItemCargoGlobal ["ACE_epinephrine", 20]; 
_veh addItemcargoglobal ["ACE_fieldDressing", 40]; 
_veh addItemCargoGlobal ["ACE_elasticBandage", 40];
_veh addItemCargoGlobal ["ACE_packingBandage", 40];
_veh addItemCargoGlobal ["ACE_quikclot", 40];
_veh addItemCargoGlobal ["ACE_tourniquet", 20];
_veh addItemCargoGlobal ["ACE_salineIV", 12];
_veh additemcargoGlobal ["ACE_surgicalKit",2];
_veh addItemCargoGlobal ["ACE_personalAidKit", 10];
_veh addItemCargoGlobal ["ACE_splint", 10];
